name: Deploy to Staging after CI Testing

on:
  workflow_run:
    workflows: ["CI Testing"]
    types:
      - completed

jobs:
  deploy-supabase:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: Staging-Supabase
      url: https://staging.celeritas-board.hu
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    permissions:
      actions: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: info-pack
          path: info-pack
      - id: get-info
        run: |
          REF=$(cat info-pack/REF)
          echo "REF=$REF" >> $GITHUB_OUTPUT
          REPO=$(cat info-pack/REPO)
          echo "REPO=$REPO" >> $GITHUB_OUTPUT
          echo REF
          echo REPO
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-info.outputs.REF }}
          repository: ${{ steps.get-info.outputs.REPO }}
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push

  deploy-apps:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Api, Houston]
    environment: ${{ matrix.environment }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    needs: deploy-supabase
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: info-pack
          path: info-pack
      - id: get-info
        run: |
          REF=$(cat info-pack/REF)
          echo "REF=$REF" >> $GITHUB_OUTPUT
          REPO=$(cat info-pack/REPO)
          echo "REPO=$REPO" >> $GITHUB_OUTPUT
          echo REF
          echo REPO
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-info.outputs.REF }}
          repository: ${{ steps.get-info.outputs.REPO }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Dump vars context
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}"
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --cwd ${{ vars.PROJECT_DIR }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --cwd ${{ vars.PROJECT_DIR }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd ${{ vars.PROJECT_DIR }}
