name: Deploy to Staging after CI Testing

on:
  workflow_run:
    workflows: ["CI Testing"]
    types:
      - completed

jobs:
  comment-on-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get_pr
        run: |
          PR_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs" \
            | jq -r '.jobs[].pull_requests[0].url' | grep -m1 '^https')
          if [ -z "$PR_URL" ]; then
            echo "No PR found for this workflow run."
            exit 1
          fi
          PR_NUMBER=$(basename $PR_URL)
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = process.env.PR_NUMBER || '${{ steps.get_pr.outputs.pr_number }}';
            if (!pr_number) {
              core.setFailed('No PR number found.');
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: "The pr is ready to be deployed on the staging environment. Ask @d0ty about it"
              });
            }
        env:
          PR_NUMBER: ${{ steps.get_pr.outputs.pr_number }}

  deploy-supabase:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging.celeritas-board.hu
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push

  deploy-api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging.celeritas-board.hu
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
    needs: deploy-supabase
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
