name: PR Test and Label
on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    branches:
      - main

jobs:
  test-and-label:
    environment:
      name: Testing
    if: |
      github.event.pull_request.base.ref == 'main' &&
      (
        github.event.action == 'opened' ||
        github.event.action == 'synchronize' ||
        github.event.action == 'labeled'
      )
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      - name: Debug env
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL\nSUPABASE_KEY=$SUPABASE_KEY" >> packages/device-comm/.env
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run tests
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: SUPABASE_URL=$SUPABASE_URL SUPABASE_KEY=$SUPABASE_KEY pnpm run test
